language: ruby
rvm:
  - 2.1
  - ruby-head
  - jruby-19mode
  - rbx-2
  - 2.2.3
  - 2.3.1
matrix:
  allow_failures:
    - rvm: ruby-head
bundler_args: --without local_development
before_install: gem install bundler
